### ISSUE TITLE
(Propuesta) Cambiar el orden en la vista principal de index

### ISSUE THREAD

**Issue by ievivas** [LESSIoT/lessiot.github.io#41]
Colocar logo en la parte izquierda.
En la parte derecha colocar:
1. "Monitoreo Eficiente"
2. Texto breve que explique lo que se monitorea. Puede ser: "Información de procesos agroindustriales, tracking y consumo electrico en tiempo real"
3. Mover el botón de acción a la sección de productos.
Hacer una captura de pantalla y mandarla al grupo para que opinen

**Comment by sebasgm** [comment]
@ievivas separá este issue en varios más chicos, algunas cosas ya están deprecadas. Las modificaciones de posición de los textos van en conjunto con el issue de hacer el slider de imágenes de fondo. El texto vamos a retocarlo. La captura ya la enviaste ;)
Finalmente el botón de call to action ya se decidió moverlo. Podés hacerlo independientemente de lo demás.
