### ISSUE TITLE
(Propuesta) Cambiar foto de background en vista principal de index

### ISSUE THREAD

**Issue by ievivas** [LESSIoT/lessiot.github.io#42]
- Se utilizará la herramienta para video background propuesta por Leandro:
https://rishabhp.github.io/bideo.js/
- Mover el botón de acción a la sección productos.
- Mover el logo al lado izquierdo y el texto del lado derecho.
- Agregar texto complementario debajo de "Monitoreo Eficiente" (preguntar)

Nota: A este issue se agregaron elementos del issue cerrado #41

**Comment by sebasgm** [comment]
Esta idea está buena Ivan. Podemos avanzar con ella. Sólo restaría revisar el texto que colocamos en esa portada, per oes en paralelo al cambio a nivel de diseño. Fijate qué imagenes seleccionar (tal vez pueden ser otras que ya están en uso en el sitio como las de los casos de uso), y hagamoslo.
