### ISSUE TITLE
Organizar styles.css

### ISSUE THREAD

**Issue by ievivas** [LESSIoT/lessiot.github.io#60]
El archivo tiene más de 7000 lineas de código.
Se debe separar e identificar los bloques de código en función de la sección HTML que representan.

**Comment by ievivas** [comment]
Dar soporte para navegadores chrome, firefox y safari a elementos CSS3 con -webkit-  y -moz-

**Comment by sebasgm** [comment]
Qué falta de este issue en lo que respecta a este milestone? Porque en principio el issues es muy amplio pero se había decidido no modificar todo el CSS sino simplemente cambiar cosas puntuales en el momento que sea necesario.

**Comment by ievivas** [comment]
El archivo css me parece un "pozo sin fondo". Me explico: En las buenas prácticas de css, aconsejan dejar al final del archivo las media rules. Estimo que el 30% del código son media rules, por lo tanto, no estaba logrando el objetivo (además de perder tiempo) haciendo esta separación.
Por otro lado, al intentar unificar selectores, estaba rompiendo elementos del sitio.
Conclusión: Creo que es mejor dejar este archivo como está, y las adiciones que voy haciendo las hago de manera organizada al final del archivo

**Comment by sebasgm** [comment]
Entonces cerramos este issue y asumimos que vamos haciendo los cambios requeridos en cada circunstancia.
