### ISSUE TITLE
Agregar/Mejorar SEO

### ISSUE THREAD

**Issue by ievivas** [LESSIoT/lessiot.github.io#61]
Utilizar la siguiente guía:
http://static.googleusercontent.com/media/www.google.com/es//intl/es/webmasters/docs/guia_optimizacion_motores_busqueda.pdf

**Comment by ievivas** [comment]
Se agregó un archivo de verificación que utiliza google para generar el sitemap.xml. Luego de hacer el pr, se debe ir a esta página para terminar con la generación del xml:
https://www.google.es/webmasters/tools/

**Comment by sebasgm** [comment]
Este issue no está listo ya?

**Comment by ievivas** [comment]
Este issue se debe actualizar después que se mergeen los cambios grandes de la página de los otros isuues.
No sé si cerrarlo y abrir otro con un SEO Update

**Comment by sebasgm** [comment]
Dejemoslo. Entiendo que lo que falta hacer no es lo que queda en el otro issue de este milestone.
