### ISSUE TITLE
Revisar y agregar casos de uso

### ISSUE THREAD

**Issue by sebasgm** [LESSIoT/lessiot.github.io#62]
Utilizo este issue como un meta issue, despues lo vamos separando:

- Agregar caso de uso en industria petrolera para monitoreo de procesos.
- Agregar medición de nivel como caso de uso separado. Hoy aplica a arroceras pero facilmente será de utilidad para tanques de ocmbustible y otras aplicaciones que ya nos estuvieron solicitando.
- Abreviar algunos textos: Esto lo vamos a ver caso por caso pero se me ocurre que podemos hacer más breves algunos de los textos en los casos de uso.

**Comment by sebasgm** [comment]
Modificaciones:

- Dejar "Productos" en plural. Porque igual la idea es que se derivan distintos productos

- Las imágenes en "Productos" se rompieron

-En "Conoce nuestros productos" dejar directamente la frase "Sensado robusto y analytics de datos" donde dice "Información e inteligencia agregada a cada proceso". Esta frase me parece que al final queda bien como descripción en la portada.

- En "Conoce nuestros productos" la idea no era dejar dos bloques uno con una foto y una con una frase. La idea es dejar un solo bloque central, más grande, con el collage de las aplicaciones de la sección de productos.

- Modificar los bullets definidos en la sección Dashboard

- Modificar los textos puestos en cada caso de uso

**Comment by ievivas** [comment]
Este meta issue fue separado en issues más pequeños, los cuales ya fueron cerrados. Por lo tanto este se cerrará también.
El único item que queda pendiente es el nuevo caso de uso de "medición de nivel" que se decidió dejarlo para más adelante cuando tengamos este producto funcionando.
