### ISSUE TITLE
Reformular sección "productos"

### ISSUE THREAD

**Issue by sebasgm** [LESSIoT/lessiot.github.io#63]
Este es otro meta issue con las ideas generales. La idea es que pivi va a ser un conjunto de variables más que se mide con nuestro producto core. Por esto no se va a ofrecer como algo independiente. Además vamos a movernos a un concepto de "producto" refiriéndonos a la propuesta de valor y bajo ese título vamos a poner textos y media de cada "aplicación" del producto:

- Remover Pivi como un producto separado
- Eliminar el título "lanza" del link a la página de la lanza
- Cambiar el subtítulo de la seccion de la lanza de "Información de procesos industriales, agrícolas, y tracking" a "Información e inteligencia agregada a cada proceso"
- Integrar la aplicación de pivi en la sección de producto de la lanza.
- En el link a la lanza cambiar la foto por un colage de las fotos de distintas aplicaciones.
- En el link a la lanza reemplazar el texto "Información de procesos agroindustriales y tracking" por "Sensado robusto | analytics de datos generados" (puesto en dos líneas).
- Agregar el item "conectividad múltiple" de la actual página de pivi a la lista de características principales de la página de la lanza.
- Fusionar la sección "Aplicaciones" dentro de la página de producto, con las imágenes y las descripciones del principio (vamos a revisar acá si algunas aplicaciones las movemos a la parte de casos de uso).

**Comment by ievivas** [comment]
Este meta issue se separó en issues más pequeños que ya están hechos y cerrados.
Por lo tanto este se cierra también.
