### ISSUE TITLE
Actualizar brochure

### ISSUE THREAD

**Issue by sebasgm** [LESSIoT/lessiot.github.io#66]
Actualmente el brochure de la sección "lanza" sólo contempla a la lanza para silo bolsa mencionando por encima la posibilidad de otros usos. Necesitamos que el brochure mencione activamente a las otras aplicaciones actuales y dé información técnica referida a los sensores. En el futuro se pueden separar varios brochures.

**Comment by tulku** [comment]
También hay que cambian los rangos de temperatura  de operación. Los que figuran son en los que se puede cargar, pero la lanza puede funcionar entre -15 y 50 C

**Comment by ievivas** [comment]
Idealmente se desean 5 brochures, uno para cada "modalidad" de la lanza:
- Lanza base: temperatura, humedad, acelerómetro, gps.
- Lanza para silo bolsa: lanza base + más sensor C02.
- Lanza para riego: lanza base + sensores de humedad de suelo.
- Lanza para niveles: lanza base + sensores niveles.
- Lanza integrada con pivi: lanza base + pivi.

**Comment by ievivas** [comment]
Por ahora, se debe crear un solo brochure con los 3 primeros items del comentario anterior.
Se creará un solo issue que incluya los 3 primeros items para anexarlo al milestone actual.
Este issue quedará abierto hasta que se decida incluir el resto de items.

**Comment by sebasgm** [comment]
Si bien el issue inicialmente habla de la posibilidad futura de varios brochure, hoy por hoy lo dejaría tal cual lo hablamos en la última call, Ivan. Solo un brochure con secciones que, además de ser menos trabajo, creo que es lo más cómodo para un cliente bajarse solo un documento y hojear las aplicaciones. Asi que trabajemos en ese documento usando la info del brochure actual y del documento para riego que está utilizando @sebascerone
